import pathlib
from ipyautoui.automapschema import pydantic_model_file_from_json_schema

predicted_energy_use_item = {'$defs': {'EnergyEndUse': {'enum': ['Heating',
    'Domestic Hot Water',
    'Heating & Domestic Hot Water',
    'Cooling',
    'Auxiliary',
    'Lighting',
    'Small Power',
    'IT/Servers',
    'PV Generation',
    'Lifts',
    'Catering',
    'Other',
    'Unknown'],
   'title': 'EnergyEndUse',
   'type': 'string'},
  'EnergyEndUseTag': {'enum': ['Heating',
    'Heating - Distribution Loss',
    'Domestic Hot Water',
    'Cooling',
    'Auxiliary',
    'Lighting',
    'Lighting - External',
    'Small Power',
    'IT/Servers',
    'PV Generation',
    'Pool',
    'Lifts',
    'Catering',
    'Other',
    'Unknown'],
   'title': 'EnergyEndUseTag',
   'type': 'string'},
  'FuelType': {'enum': ['Electricity',
    'Gas - NG',
    'Gas - Biogas',
    'Gas - LPG',
    'Gas - Other',
    'Unknown',
    'Unset'],
   'title': 'FuelType',
   'type': 'string'},
  'OperationalEnergyAnalysisType': {'enum': ['Part L',
    'Scottish Part L',
    'TM54',
    'Passivhaus',
    'Custom'],
   'title': 'OperationalEnergyAnalysisType',
   'type': 'string'},
  'PredictedEnergyUseItem': {'properties': {'InstanceReference': {'anyOf': [{'type': 'integer'},
      {'type': 'null'}],
     'default': 1,
     'description': 'equipment instance reference, integer only. Refers to equipment instance.',
     'title': 'Instance Reference'},
    'BuildingID': {'anyOf': [{'type': 'string'}, {'type': 'null'}],
     'default': None,
     'description': 'A unique identifier within the project assigned to a building',
     'title': 'Building ID'},
    'AssessmentDate': {'anyOf': [{'format': 'date', 'type': 'string'},
      {'type': 'null'}],
     'default': None,
     'description': 'Date on which the overall condition is assessed',
     'title': 'Assessment Date'},
    'Notes': {'anyOf': [{'type': 'string'}, {'type': 'null'}],
     'default': None,
     'description': '',
     'title': 'Notes'},
    'OperationalEnergyAnalysisType': {'anyOf': [{'$ref': '#/$defs/OperationalEnergyAnalysisType'},
      {'type': 'null'}],
     'default': None,
     'description': 'defines the type of analysis',
     'title': 'Operational Energy Analysis Type'},
    'FuelType': {'anyOf': [{'$ref': '#/$defs/FuelType'}, {'type': 'null'}],
     'default': None,
     'description': '',
     'title': 'Fuel Type'},
    'EnergyConsumption': {'anyOf': [{'type': 'number'}, {'type': 'null'}],
     'default': None,
     'description': 'Annual energy consumption requirement. NOTE: PV Generation should be a -ve value.',
     'title': 'Energy Consumption'},
    'EnergyEndUse': {'anyOf': [{'$ref': '#/$defs/EnergyEndUse'},
      {'type': 'null'}],
     'default': None,
     'description': 'The end-use of the energy consumption within a building. Pick the most appropriate.',
     'title': 'Energy End Use'},
    'EnergyEndUseTags': {'anyOf': [{'items': {'$ref': '#/$defs/EnergyEndUseTag'},
       'type': 'array'},
      {'type': 'null'}],
     'default': None,
     'description': 'Avoid where possible. Use only when the "Energy End Use" does not correctly describe usage (e.g. mostly DHW, but add a lighting tag to indicate some lights).',
     'title': 'Energy End Use Tags'},
    'TypeMark': {'anyOf': [{'type': 'string'}, {'type': 'null'}],
     'default': None,
     'description': '',
     'title': 'Type Mark'},
    'TypeSpecId': {'anyOf': [{'type': 'integer'}, {'type': 'null'}],
     'default': None,
     'description': '',
     'title': 'Type Spec Id'},
    'Id': {'anyOf': [{'type': 'integer'}, {'type': 'null'}],
     'default': None,
     'description': '',
     'title': 'Id'}},
   'title': 'PredictedEnergyUseItem',
   'type': 'object'}},
 'items': {'$ref': '#/$defs/PredictedEnergyUseItem'},
 'title': 'PredictedEnergyUse',
 'type': 'array'}

fpth=pathlib.Path("pydantic-model-predicted_energy_use_item.py")
model_file = pydantic_model_file_from_json_schema(predicted_energy_use_item, fpth)



project_building_area_schema = {'title': 'Project Building Area',
 'type': 'array',
 'format': 'DataFrame',
 'hide_nan': True,
 'datagrid_index_name': ['section', 'title'],
 'items': {'title': 'Project Buildings',
  'description': 'Add any buildings that exist within the project',
  'type': 'object',
  'parameter_type': 'T',
  'override_units': True,
  'classification': '',
  'properties': {'Abbreviation': {'enum': ['BLDG'],
    'type': 'string',
    'revit_data_type': 'TEXT',
    'ifc_data_type': 'IfcText',
    'namespace_uri': None,
    'guid': '4ec7e9b3-b1f0-4b76-b0d4-9dd1338b8c2f',
    'guid_source': 'MXF',
    'title': 'Abbreviation',
    'name': 'Abbreviation',
    'description': 'equipment type abbreviation, alphabetic characters only, variable length, between 2 and 6 characters',
    'category': 'Specifications',
    'section': 'Identity Data',
    'tooltip': 'asset abbreviation is defined by the [BDNS](https://github.com/theodi/BDNS). Abbreviations must be from those defined in the [BDNS_Abbreviations_Register.csv](https://github.com/theodi/BDNS/blob/master/BDNS_Abbreviations_Register.csv)',
    'property_value_kind': 'Single',
    'unit': '',
    'unit_code': '',
    'parameter_type': 'T',
    'pset': 'Pset_IdentityCore',
    'id': 2696,
    'default': 'BLDG'},
   'TypeReference': {'type': 'integer',
    'revit_data_type': 'INTEGER',
    'ifc_data_type': 'IfcInteger',
    'namespace_uri': None,
    'guid': 'f2cb3fad-ff04-4e62-bffa-80d6d3fd2862',
    'guid_source': 'MXF',
    'title': 'Type Reference',
    'name': 'TypeReference',
    'description': 'equipment type reference, integer only. Refers to equipment type, there may be multiple instances of the same type',
    'category': 'Specifications',
    'section': 'Identity Data',
    'tooltip': '',
    'property_value_kind': 'Single',
    'unit': '',
    'unit_code': '',
    'parameter_type': 'T',
    'pset': 'Pset_IdentityCore',
    'id': 2698,
    'default': 1},
   'TargetYear': {'enum': [2025,
     2026,
     2027,
     2028,
     2029,
     2030,
     2031,
     2032,
     2033,
     2034,
     2035,
     2036,
     2037,
     2038,
     2039,
     2040,
     2050],
    'revit_data_type': 'INTEGER',
    'ifc_data_type': 'IfcInteger',
    'namespace_uri': None,
    'guid': '38d4ec6a-9fbb-458f-88a2-b29b33c1ec48',
    'guid_source': 'MXF',
    'title': 'Target Year',
    'name': 'TargetYear',
    'description': 'Net Zero Carbon targets change annually. This defined what year the Benchmark Targets should be defined by.',
    'category': 'Specifications',
    'section': 'Identity Data',
    'tooltip': None,
    'property_value_kind': 'Single',
    'unit': '',
    'unit_code': '',
    'parameter_type': 'T',
    'pset': 'BuildingArea',
    'id': 3090,
    'type': 'integer'},
   'Name': {'revit_data_type': 'TEXT',
    'ifc_data_type': 'IfcText',
    'namespace_uri': 'https://identifier.buildingsmart.org/uri/buildingsmart/ifc/4.3/prop/Name',
    'guid': 'a13b623a-94ea-4864-a42c-76d3a40acd47',
    'guid_source': 'MXF',
    'title': 'Building Name',
    'name': 'Name',
    'description': 'Optional. Add a building name as used in the project for easier identification.',
    'category': 'Facilities/Asset Management',
    'section': 'Identity Data',
    'tooltip': None,
    'property_value_kind': 'Single',
    'unit': '',
    'unit_code': '',
    'parameter_type': 'T',
    'pset': 'BuildingArea',
    'id': 3091,
    'type': 'string'},
   'Id': {'format': 'default',
    'revit_data_type': 'INTEGER',
    'ifc_data_type': 'IfcInteger',
    'namespace_uri': None,
    'guid': '958e6995-9f04-49d3-ba03-738b6bd66fd0',
    'guid_source': 'MXF',
    'title': 'Id',
    'name': 'Id',
    'description': '',
    'category': 'Undefined',
    'section': 'Identity Data',
    'tooltip': None,
    'property_value_kind': 'Single',
    'unit': '',
    'unit_code': '',
    'parameter_type': 'T',
    'pset': '',
    'id': 0,
    'type': 'integer'}},
  'id': 835}}

fpth=pathlib.Path("pydantic-model-project-building-area.py")
model_file = pydantic_model_file_from_json_schema(project_building_area_schema, fpth)

building_type_schema = {'$defs': {'BuildingType': {'enum': ['Commercial Resi - Student Residential',
    'Commercial Resi - Care Home',
    'Culture & Enterainment - Performance',
    'Culture & Enterainment - Collection (e.g. museum)',
    'Culture & Enterainment - Archive',
    'Healthcare',
    'Healthcare - Acute Trust',
    'Healthcare - Care Trust',
    'Healthcare - Community Trust',
    'Healthcare - Mental Health & Learning Trust',
    'Healthcare - Ambulance Trust',
    'Higher Education',
    'Homes - Single family homes',
    'Homes - Flats',
    'Hotel',
    'Office - General',
    'Office - Call Centre',
    'Office - Trading Floors',
    'Retail - Supermarket',
    'Retail - High street retail e.g. dept. store',
    'Retail - F&B without catering (a)',
    'Retail - F&B with catering (b)',
    'Retail - Landlord areas (c)',
    'Retail - warehouse',
    'School - Early years',
    'School - Primary',
    'School - Secondary or SEN',
    'Science and Technology',
    'Sport & Leisure - Dry',
    'Sport & Leisure - Wet',
    'Sport & Leisure - Fitness',
    'Storage & Distribution - Unconditioned',
    'Storage & Distribution - Conditioned',
    'Storage & Distribution - Cold Store'],
   'title': 'BuildingType',
   'type': 'string'},
  'ProjectBuildingAreaItem': {'properties': {'InstanceReference': {'anyOf': [{'type': 'integer'},
      {'type': 'null'}],
     'default': 1,
     'description': 'equipment instance reference, integer only. Refers to equipment instance.',
     'title': 'Instance Reference'},
    'BuildingType': {'anyOf': [{'$ref': '#/$defs/BuildingType'},
      {'type': 'null'}],
     'default': None,
     'description': 'Description of what the building (or subset of building) is used for. Must match with types from reference XXX',
     'title': 'Building Type'},
    'GrossInternalArea': {'anyOf': [{'type': 'number'}, {'type': 'null'}],
     'default': None,
     'description': 'all area internal of the perimeter walls of the building (not including the perimeter wall build-up).\n\nhttps://www.designingbuildings.co.uk/wiki/Gross_internal_area_GIA',
     'title': 'Gross Internal Area'},
    'IsNewBuild': {'anyOf': [{'type': 'boolean'}, {'type': 'null'}],
     'default': None,
     'description': 'is the building (or subset of building) a new build or refurb?',
     'title': 'Is New Build'},
    'TypeMark': {'anyOf': [{'type': 'string'}, {'type': 'null'}],
     'default': None,
     'description': 'Select the building to link the area to',
     'title': 'Building ID'},
    'TypeSpecId': {'anyOf': [{'type': 'integer'}, {'type': 'null'}],
     'default': None,
     'description': '',
     'title': 'Type Spec Id'},
    'Id': {'anyOf': [{'type': 'integer'}, {'type': 'null'}],
     'default': None,
     'description': '',
     'title': 'Id'}},
   'title': 'ProjectBuildingAreaItem',
   'type': 'object'}},
 'items': {'$ref': '#/$defs/ProjectBuildingAreaItem'},
 'title': 'ProjectBuildingArea',
 'type': 'array'}

fpth=pathlib.Path("pydantic-model-building-type.py")
model_file = pydantic_model_file_from_json_schema(building_type_schema, fpth)

uset_type_area_schema = {'title': 'Project Building Area',
 'type': 'array',
 'format': 'DataFrame',
 'hide_nan': True,
 'datagrid_index_name': ['section', 'title', 'unit'],
 'items': {'title': 'Project Building Area',
  'description': 'Entry for the area of a building or sub-section of a building',
  'type': 'object',
  'parameter_type': 'I',
  'override_units': True,
  'classification': '',
  'properties': {'InstanceReference': {'type': 'integer',
    'revit_data_type': 'INTEGER',
    'ifc_data_type': 'IfcInteger',
    'namespace_uri': None,
    'guid': '2705c5f3-e588-4d32-aac4-3bba358c898b',
    'guid_source': 'MXF',
    'title': 'Instance Reference',
    'name': 'InstanceReference',
    'description': 'equipment instance reference, integer only. Refers to equipment instance.',
    'category': 'Specifications',
    'section': 'Identity Data',
    'tooltip': '',
    'property_value_kind': 'Single',
    'unit': '',
    'unit_code': '',
    'parameter_type': 'I',
    'pset': 'Pset_IdentityCore',
    'id': 2866,
    'default': 1},
   'BuildingType': {'enum': ['Commercial Resi - Student Residential',
     'Commercial Resi - Care Home',
     'Culture & Enterainment - Performance',
     'Culture & Enterainment - Collection (e.g. museum)',
     'Culture & Enterainment - Archive',
     'Healthcare',
     'Healthcare - Acute Trust',
     'Healthcare - Care Trust',
     'Healthcare - Community Trust',
     'Healthcare - Mental Health & Learning Trust',
     'Healthcare - Ambulance Trust',
     'Higher Education',
     'Homes - Single family homes',
     'Homes - Flats',
     'Hotel',
     'Office - General',
     'Office - Call Centre',
     'Office - Trading Floors',
     'Retail - Supermarket',
     'Retail - High street retail e.g. dept. store',
     'Retail - F&B without catering (a)',
     'Retail - F&B with catering (b)',
     'Retail - Landlord areas (c)',
     'Retail - warehouse',
     'School - Early years',
     'School - Primary',
     'School - Secondary or SEN',
     'Science and Technology',
     'Sport & Leisure - Dry',
     'Sport & Leisure - Wet',
     'Sport & Leisure - Fitness',
     'Storage & Distribution - Unconditioned',
     'Storage & Distribution - Conditioned',
     'Storage & Distribution - Cold Store'],
    'revit_data_type': 'TEXT',
    'ifc_data_type': 'IfcText',
    'namespace_uri': None,
    'guid': 'c3108630-93b0-4bd2-b30c-6e37f370aea8',
    'guid_source': 'MXF',
    'title': 'Building Type',
    'name': 'BuildingType',
    'description': 'Description of what the building (or subset of building) is used for. Must match with types from reference XXX',
    'category': 'Specifications',
    'section': 'Application',
    'tooltip': None,
    'property_value_kind': 'Single',
    'unit': '',
    'unit_code': '',
    'parameter_type': 'I',
    'pset': 'BuildingArea',
    'id': 3088,
    'type': 'string'},
   'GrossInternalArea': {'revit_data_type': 'AREA',
    'ifc_data_type': 'IfcAreaMeasure',
    'namespace_uri': None,
    'guid': '0f5ba3d3-d2eb-4b94-b6f1-faed9db068f3',
    'guid_source': 'MXF',
    'title': 'Gross Internal Area',
    'name': 'GrossInternalArea',
    'description': 'all area internal of the perimeter walls of the building (not including the perimeter wall build-up).\n\nhttps://www.designingbuildings.co.uk/wiki/Gross_internal_area_GIA',
    'category': 'Specifications',
    'section': 'Dimensions',
    'tooltip': None,
    'property_value_kind': 'Single',
    'unit': 'm²',
    'unit_code': 'm**2',
    'parameter_type': 'I',
    'pset': 'BuildingArea',
    'id': 3086,
    'type': 'number'},
   'IsNewBuild': {'revit_data_type': 'YESNO',
    'ifc_data_type': 'IfcBoolean',
    'namespace_uri': None,
    'guid': '1d2bcf6f-885d-4434-bd99-af248eb97ed2',
    'guid_source': 'MXF',
    'title': 'Is New Build',
    'name': 'IsNewBuild',
    'description': 'is the building (or subset of building) a new build or refurb?',
    'category': 'Specifications',
    'section': 'Dimensions',
    'tooltip': None,
    'property_value_kind': 'Single',
    'unit': '',
    'unit_code': '',
    'parameter_type': 'I',
    'pset': 'BuildingArea',
    'id': 3089,
    'type': 'boolean'},
   'TypeMark': {'enum': ['BLDG-1', 'BLDG-3', 'BLDG-4'],
    'type': 'string',
    'revit_data_type': 'TEXT',
    'ifc_data_type': 'IfcText',
    'namespace_uri': None,
    'guid': '95cba5f9-706b-49e1-9100-c423f2c1f6f5',
    'guid_source': 'MXF',
    'title': 'Building ID',
    'name': 'BuildingID',
    'description': 'Select the building to link the area to',
    'category': 'Undefined',
    'section': 'Identity Data',
    'tooltip': None,
    'property_value_kind': 'Single',
    'unit': '',
    'unit_code': '',
    'parameter_type': 'I',
    'pset': '',
    'id': 0,
    'autoui': 'ipywidgets.Dropdown'},
   'TypeSpecId': {'format': 'default',
    'revit_data_type': 'INTEGER',
    'ifc_data_type': 'IfcInteger',
    'namespace_uri': None,
    'guid': 'f5bdea0b-8648-43a6-b85a-5cc443d86e8e',
    'guid_source': 'MXF',
    'title': 'Type Spec Id',
    'name': 'TypeSpecId',
    'description': '',
    'category': 'Undefined',
    'section': 'Identity Data',
    'tooltip': None,
    'property_value_kind': 'Single',
    'unit': '',
    'unit_code': '',
    'parameter_type': 'I',
    'pset': '',
    'id': 0,
    'type': 'integer'},
   'Id': {'format': 'default',
    'revit_data_type': 'INTEGER',
    'ifc_data_type': 'IfcInteger',
    'namespace_uri': None,
    'guid': '958e6995-9f04-49d3-ba03-738b6bd66fd0',
    'guid_source': 'MXF',
    'title': 'Id',
    'name': 'Id',
    'description': '',
    'category': 'Undefined',
    'section': 'Identity Data',
    'tooltip': None,
    'property_value_kind': 'Single',
    'unit': '',
    'unit_code': '',
    'parameter_type': 'I',
    'pset': '',
    'id': 0,
    'type': 'integer'}},
  'id': 835}}

fpth=pathlib.Path("pydantic-model-use-type-area.py")
model_file = pydantic_model_file_from_json_schema(uset_type_area_schema, fpth)
