# TODO: setup auto-update pixi.lock https://pixi.sh/latest/advanced/updates_github_actions/#how-to-use

name: Test and Lint

on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
            manifest-path: pyproject.toml
            pixi-version: v0.41.1
            cache: true
            cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - run: pixi run tests
